// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "agarwalconsulting.io/rvstore/products/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	IndexEndpoint       endpoint.Endpoint
	IndexSecureEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.ProductsService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		IndexEndpoint:       MakeIndexEndpoint(s),
		IndexSecureEndpoint: MakeIndexSecureEndpoint(s),
	}
	for _, m := range mdw["Index"] {
		eps.IndexEndpoint = m(eps.IndexEndpoint)
	}
	for _, m := range mdw["IndexSecure"] {
		eps.IndexSecureEndpoint = m(eps.IndexSecureEndpoint)
	}
	return eps
}
