apiVersion: v1
kind: Secret
metadata:
  name: mongosecret
type: Opaque
data:
  username: cm9vdAo=
  password: ZXhhbXBsZQo=
  connection: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nb2RiLXNlcnZpY2UvYWRtaW4K

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 500m
            memory: 100Mi
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongosecret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongosecret
              key: password
        volumeMounts:
          - name: mongodata
            mountPath: /data/db
      volumes:
      - name: mongodata
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-service
  name: mongodb-service
spec:
  ports:
  - name: dbport
    port: 27017
    targetPort: 27017
  selector:
    app: mongo
